In [1]:
import math
import numpy as np

%matplotlib inline

import matplotlib
import numpy as np
import matplotlib.pyplot as plt

In [2]:
def calc_dx1(t, x1, x2):
    return -0.5 * x1 + 0.1 * abs(np.sin(3 * t)) * x2

def calc_dx2(t, x1, x2):
    return np.exp(np.sin(t)) * x1 + 0.5 * x2

In [3]:
def solve_koshi(x1_0, x2_0, max_t = 2*math.pi):
    current_t = 0.0
        
    x1 = x1_0
    x2 = x2_0
        
    while current_t < max_t:
        dx1 = calc_dx1(current_t, x1, x2)
        dx2 = calc_dx2(current_t, x1, x2)
        
        step = 0.00001 
        x1 += dx1 * step
        x2 += dx2 * step
        current_t += step
                
    return x1, x2

    

In [4]:
u1, u2 = solve_koshi(1, 0)

In [5]:
v1, v2 = solve_koshi(0, 1)

In [6]:
m = np.array([[u1, v1], [u2, v2]])

In [7]:
m

array([[  3.19124874,   2.01338623],
       [ 52.85985932,  33.66308954]])

In [8]:
evalues, vectors = np.linalg.eig(m)

In [9]:
evalues, vectors

(array([  2.71532898e-02,   3.68271850e+01]),
 array([[-0.536851  , -0.05975124],
        [ 0.84367707, -0.9982133 ]]))

In [9]:
ev1 = vectors[:, 0]
ev2 = vectors[:, 1]

In [10]:
print(ev1)
print(ev1 * evalues[0])
print(ev1 * evalues[0] * evalues[0])

[-0.536851    0.84367707]
[-0.01457727  0.02290861]
[-0.00039582  0.00062204]


In [11]:
solve_koshi(ev1[0], ev1[1], 2 * math.pi)

(-0.014577270768672868, 0.02290860811073725)

In [12]:
solve_koshi(ev1[0], ev1[1], 4 * math.pi)

(-0.00039589957965375648, 0.00062072893556464526)

In [13]:
print(ev2)
print(ev2 * evalues[1])
print(ev2 * evalues[1] * evalues[1])

[-0.05975124 -0.9982133 ]
[ -2.20046998 -36.76138581]
[  -81.03711514 -1353.81835591]


In [14]:
solve_koshi(ev2[0], ev2[1], 2 * math.pi)

(-2.2004699828600494, -36.761385809051582)

In [15]:
solve_koshi(ev2[0], ev2[1], 4 * math.pi)

(-81.036747026888108, -1353.8189344374146)